{
  pkgs,
  lib,
  src,
  ...
}:
let
  # with extraLuaPackages defined hm will try to add init.lua due, which conflicts with my init.lua
  # here we replicate the hm logic and generate a separate lua file that we will later import in init.lua
  x = pkgs.neovim-unwrapped.lua.pkgs;
  luaPackages = with x; [
    fzf-lua
    fzy
    jsregexp # for luasnip
    luasnip
    luv
    sqlite
  ];

  generatedLuaPath = lib.concatMapStringsSep ";" x.getLuaPath luaPackages;
  generatedLuaCPath = lib.concatMapStringsSep ";" x.getLuaCPath luaPackages;

  luaPackagesFile = ''
    -- generated by home-manager

    -- lua package paths
    package.path = "${generatedLuaPath}" .. ";" .. package.path
    package.cpath = "${generatedLuaCPath}" .. ";" .. package.cpath
  '';
in
{
  xdg = {
    enable = true;
    configFile = {
      "conda" = {
        recursive = true;
        source = "${src}/conf.d/conda";
      };
      "python" = {
        recursive = true;
        source = "${src}/conf.d/python";
      };
      "glow" = {
        recursive = true;
        source = "${src}/conf.d/glow";
      };
      "npm" = {
        recursive = true;
        source = "${src}/conf.d/npm";
      };
      "wget" = {
        recursive = true;
        source = "${src}/conf.d/wget";
      };
      "yarn" = {
        recursive = true;
        source = "${src}/conf.d/yarn";
      };
      # generate a separate file for the lua cpath/path
      # this must be imported by the init.lua file
      "nvim/init.lua".enable = false;
      "nvim/lua/home-manager.lua".text = luaPackagesFile;

    };
  };
}
