creation_rules:
  - path_regex: conf\.d/sops/secrets\.yaml$
    age: >-
      age1cc2n5xttywv2t86xmtpkg0fptgfkjflvqxzcrwavmpfjmkfrhsuskdh65q,
      age1c0rk88eall59su5x4vfqrqtqskkdd3qnj5eyd93ve8wa6jmcx3dsmkzdx2,
      age1pzwzf6lqjsjgpys0jlwfc957xewhclfr7hxg5wftky0q4cunwsequqyysa,
      age1hwpy5jpkm6kyvr2apppq5scceu5ypsqa8unptmrzry3pu37swygqcc7ca6,
      age1ma2h46jzrp3ux5gx6ad9l5yap7t60pl2jw0jevd9d6yn7k407yws3ws9sx,
      age10yxsamlz7rtc2lq4g5wtjdhktrycz4hlsyj7hrv86lrqaasumprsaskk0r,
      age1mg3w0fvrcxn5hxea5wljdqshel3l2lykv9l62ux2nfnyt3ck4yzq6jq4v3,
      age19tmhkq52a077pnrhu6svd05vm45wuffxfmkmgzdczgl03f3z5uusde3myg,
      age1qrk5dqfnzhd9sy5ujd0p3q6gky0hztn3mrv5gzcj9yutcdu2552qflgy6s,
      age1a8gvyt8zw5qm0t752cezs5e7dfmymxqlqvw59vgu9kjnhj0aks2q3e937e,
      age1adjpe4mz7sqpq4xcsz9kpss4a5pa906aysk9ldjhc4a35ut5ycrs5f4hmd,
      age1wh4xsa6czp5q7q0qzjxujptkw84hh8y3u6greuudyvv3c4wlmgxqk580um
