[settings]
jobs = 16
task.output = "keep-order"

# ------------------------------------------------------------------------------
[tools]
bun = "latest"

# ------------------------------------------------------------------------------
[env]

# ------------------------------------------------------------------------------
[task_config]
includes = [".mise/tasks"]

# ==============================================================================
#  Setup
# ==============================================================================
[tasks."setup:init"]
run = [
  "echo [INFO] Checking necessary pakcgges",
  { tasks = [
    "setup:apt-check curl",
    "setup:apt-check openssl",
    "setup:apt-check zsh",
    "setup:apt-check git",
    "setup:apt-check age",
  ] },
  { tasks = ["repo:remote-url", "setup:trusted-user", "setup:zsh"] },
  { task = "nix:daemon-restart" },
  { task = "setup:mise-install" },
]

# mise sync-transient-prompt: update colors in plugins.zsh after changing theme
