# treefmt.nix
{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";

  programs = {
    nixfmt = {
      enable = pkgs.lib.meta.availableOn pkgs.stdenv.buildPlatform pkgs.nixfmt.compiler;
      package = pkgs.nixfmt;
    };
    statix = {
      enable = true;
      package = pkgs.statix;
    };
    deadnix = {
      enable = true;
      package = pkgs.deadnix;
    };
  };

  # Override the default settings generated by the above option
  # settings.formatter = {
  #   terraform.excludes = [ "hello.tf" ];
  # };
}
