{
  config,
  pkgs,
  lib,
  ...
}:
{
  mise = {
    enable = true;
    enableBashIntegration = false; # completion must be generated by the runtime bootstrap
    enableZshIntegration = false; # activated below without smartcache
    globalConfig = {
      tools = {
        # Runtimes and package managers
        # npm backend; lifecycle scripts stay jailed. The vendor publishes a signed
        # packslip, which pins the release signer and checks host requirements, so
        # it needs neither the stale aqua registry entry nor the github backend.
        "packslip:github.com/aubepkg/aube" = "latest";
        cargo-binstall = "latest"; # install cargo tools from prebuilt releases
        go = "latest";
        node = "latest"; # runtime for npm tools and nub
        python = "latest";
        uv = "latest";

        # LSP
        "aqua:LuaLS/lua-language-server" = "latest";
        "aqua:artempyanykh/marksman" = "latest";
        "aqua:astral-sh/ruff" = "latest";
        "aqua:hashicorp/terraform-ls" = "latest";
        "aqua:terraform-linters/tflint" = "latest";
        "cargo:shuck-cli" = "latest"; # shell LSP and linter; replaces bash-language-server
        "github:kristoff-it/superhtml" = "latest"; # HTML LSP and formatter
        "github:neocmakelsp/neocmakelsp" = "latest";
        "github:tombi-toml/tombi" = {
          version = "latest";
          exe = "tombi";
        }; # musl-only Linux releases
        "go:golang.org/x/tools/gopls" = "latest";
        "npm:@actions/languageserver" = "latest";
        "npm:dockerfile-language-server-nodejs" = "latest";
        "npm:vscode-langservers-extracted" = "latest";
        "npm:yaml-language-server" = "latest";
        "pipx:zuban" = "latest";

        # Formatters
        "go:golang.org/x/tools/cmd/goimports" = "latest";
        "go:mvdan.cc/gofumpt" = "latest";
        "npm:fixjson" = "latest";
        "npm:prettier" = "latest";
        "pipx:beautysh" = "latest";
        "pipx:cmakelang" = {
          version = "latest";
          extras = "YAML";
        }; # cmake-format with YAML config support

        # Linters
        "aqua:hadolint/hadolint" = "latest";
        "aqua:koalaman/shellcheck" = "latest";
        "aqua:rhysd/actionlint" = "latest";
        "github:immanuwell/dockerfile-roast" = {
          version = "latest";
          exe = "droast";
        }; # Dockerfile linter
        "go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest";
        "npm:markdownlint-cli2" = "latest";
        "npm:oxlint" = "latest";
        "pipx:systemdlint" = "latest";

        # DAP
        # Lazy: nvim-dap starts it by command name through the shim, so the first
        # debug session installs it; nothing else calls it by absolute path.
        "github:vadimcn/codelldb" = {
          version = "latest";
          bin_path = "extension/adapter"; # executable is nested in the release archive
          lazy = true;
          lazy_bins = [ "codelldb" ];
        };
        "go:github.com/go-delve/delve/cmd/dlv" = "latest";

        # General CLI tools
        nub = "latest"; # Node toolchain frontend; requires node
        usage = "latest";
        # ruby = "latest";
        # Interactive CLIs nothing invokes on PATH except a human: lazy, so a
        # fresh machine does not download them until first use. Non-registry
        # backends must name their commands in lazy_bins.
        "github:dmtrKovalenko/bashka" = "latest"; # Claude Code hook; must exist before any session
        "go:github.com/perplexityai/bumblebee/cmd/bumblebee" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "bumblebee" ];
        };
        "go:github.com/retlehs/quien" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "quien" ];
        };
        "go:golang.org/x/vuln/cmd/govulncheck" = "latest"; # project-wide Go vulnerability scanner
        "npm:@rivolink/leaf" = "latest";
        # Cloudflare CLI; replaces flarectl and wrangler. opentofu and
        # cf-terraforming stay pinned in home-lab's cloudflare/.mise/tasks/cf/*
        # #MISE tools headers because they are tied to the tofu state format.
        # Stays on npm:cf rather than the `cloudflare-cf` registry alias: the alias
        # needs a pinned beta while cf is pre-1.0, which would stop auto-updates.
        "npm:cf" = "latest";
      }
      // lib.optionalAttrs pkgs.stdenv.hostPlatform.isDarwin {
        "github:docker/compose" = "latest"; # avoid the deprecated aqua alias
        "aqua:docker/buildx" = "latest"; # nixpkgs can lag upstream
        "aqua:docker/cli" = "latest"; # colima's VM auto-updates dockerd; keep the client in step

        # Code agent tools. Lazy: MCP servers are started by the agent client by
        # command name and the CLIs are used by hand, so the shim installs them on
        # first call instead of on every machine bootstrap.
        "npm:@aloth/olcli" = {
          version = "latest";
          lazy = true;
          lazy_bins = [
            "olcli"
            "olcli-mcp"
            "git-remote-overleaf"
          ];
        }; # Overleaf CLI: sync, compile, files, comments
        "npm:@google-cloud/backupdr-mcp" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "backupdr-mcp" ];
        };
        "npm:@google-cloud/gcloud-mcp" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "gcloud-mcp" ];
        };
        "npm:@google-cloud/observability-mcp" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "observability-mcp" ];
        };
        "npm:@google-cloud/storage-mcp" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "storage-mcp" ];
        };
        "npm:@hackmd/hackmd-cli" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "hackmd-cli" ];
        };
        "npm:@netique/overleaf-mcp" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "overleaf-mcp" ];
        }; # Overleaf MCP over Socket.IO OT; edits land as tracked changes
        "npm:@readwise/cli" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "readwise" ];
        };
        "npm:tokscale" = {
          version = "latest";
          lazy = true;
          lazy_bins = [ "tokscale" ];
        };
      };
      settings = {
        # https://mise.jdx.dev/configuration/settings.html

        always_keep_download = false;
        always_keep_install = false;
        auto_install = true; # install missing tools on execution
        color_theme = "catppuccin";
        env_file = ".env";
        experimental = true;
        fetch_remote_versions_timeout = "60s";
        github = {
          credential_command = "gh auth token";
        };
        gpg_verify = true;
        jobs = 8;
        libc = "gnu"; # avoid mise's musl host misdetection
        minimum_release_age = "0s"; # duration string; integer 0 is invalid
        paranoid = false;
        use_versions_host = false; # bypass the flaky mise-versions CDN
        task = {
          output = "keep-order";
        };

        # Keep the OS interpreter behind these names so macOS scripts that expect
        # the system python keep working; mise's own build stays reachable as
        # python3.<minor>. Only shims are affected: under `mise activate` the tool
        # bin directory still joins PATH.
        shims = {
          exclude = [
            "python"
            "python3"
            "pip"
            "pip3"
          ];
        };

        # packslip tools ship agent skills (usage, aube). Link them into the
        # ~/.agents/skills hub that ~/.config/{claude,grok}/skills already
        # symlink into, after every install and `mise use`. skills.dir is
        # documented as project-relative, but an absolute path is honoured
        # as-is (verified on 2026.10.0 from both project and non-project dirs).
        skills = {
          dir = "${config.home.homeDirectory}/.agents/skills";
          auto_sync = true;
        };

        cargo = {
          binstall = true;
        };

        npm = {
          package_manager = "aube";
        };

        python = {
          uv_venv_auto = true;
        };

        # config files with these prefixes will be trusted by default
        trusted_config_paths = [
          "~/.config/mise"
          "~/.config/nvim"
          "~/.config/home-manager"
          "/opt/stacks"
          "~/Workspace"
          "~/Work"
        ];

        # configure messages displayed when entering directories with config files
        status = {
          missing_tools = "if_other_versions_installed";
          show_env = false;
        };
      };
    };
  };

  bash.initExtra = lib.mkOrder 1010 ''
    eval "$(${lib.getExe pkgs.mise} activate bash)"
    if [[ -r "''${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/mise.bash" ]]; then
      source "''${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/mise.bash"
    fi
  '';

  # Load mise without smartcache after cached integrations and before custom hooks.
  zsh.initContent = lib.mkOrder 1010 ''
    eval "$(${lib.getExe pkgs.mise} activate zsh)"
    # The native wrapper may create _mise after compinit on its first run.
    if (( $+functions[compdef] )) && [[ -r "$XDG_DATA_HOME/zsh/site-functions/_mise" ]]; then
      autoload -Uz _mise
      compdef _mise mise
    fi
  '';
}
