#!/usr/bin/env bash
#MISE description="Install nix(DeterminateSystems)"
#MISE raw=true

set -euo pipefail

echo "Starting nix installation..."

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm

echo "Completed nix installation."

# vim: ft=sh
