#!/usr/bin/env bash
#MISE description="Update transient prompt colors from starship palette"

set -euo pipefail

echo "Updated login shell for $USER to /usr/bin/zsh"

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm

echo "Updated login shell for $USER to /usr/bin/zsh"

# vim: ft=sh
