[misc]
disable = [
  "bun",
  "bun_packages",
  "cargo",
  "clam_av_db",
  "containers",
  "gcloud",
  "gem",
  "github_cli_extensions",
  "go",
  "mamba",
  "node",
  "poetry",
  "pnpm",
  "pyenv",
  "rye",
  "uv",
  "vim",
  "yarn",
  "yazi",
]
