"""User-run only: python3 -I key_admin.py <public-runtime.json> [upload|confirm|restore].

The default action is upload. Runtime JSON has exactly doppler_binary, project,
doppler_config and api_host. No AWS operations, expiry policy, direct credential
reads, automatic selection of historical keys, or client switching occur here.
Doppler itself uses the operator's existing login, or a hidden user-token input.
Commit states describe this write attempt (confirm: the supplied event), not
whether a key was ever deployed. No result authorizes revoking either AWS key.
"""

from __future__ import annotations

import getpass
import json
import os
import re
import selectors
import signal
import stat
import subprocess
import sys
import time
import warnings
from collections.abc import Callable, Iterator, Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime
from itertools import pairwise
from pathlib import Path
from typing import BinaryIO, cast

SECRET = "AWS_BEARER_TOKEN_BEDROCK"
PROJECT = "dot-nix"
CONFIG = "dev_personal"
API_HOST = "https://api.doppler.com"
ACTIONS = ("upload", "confirm", "restore")
MAX_SECRET = 4096
MAX_RUNTIME = 8192
MAX_OUTPUT = 1024 * 1024
HISTORY_LIMIT = 20
COMMAND_TIMEOUT = 15.0
COMMAND_BUDGET = 120.0
CLEANUP_TIMEOUT = 0.5
NIX_BINARY = re.compile(r"/nix/store/[0-9a-df-np-sv-z]{32}-[^/\s]+/bin/doppler")
IDENTIFIER = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,127}")
TIMESTAMP = re.compile(
    r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})"
)
REASONS = frozenset(
    {
        "verified_event_and_value",
        "invalid_arguments",
        "invalid_runtime",
        "invalid_input",
        "input_unavailable",
        "user_declined",
        "unsupported_platform",
        "user_config_unavailable",
        "user_config_permissions",
        "executable_unavailable",
        "local_permission_denied",
        "permission_or_authentication",
        "cli_error",
        "invalid_response",
        "unreadable_secret",
        "workplace_mismatch",
        "identity_changed",
        "history_unavailable",
        "event_not_single_key",
        "event_value_mismatch",
        "later_target_edit",
        "concurrent_change",
        "presence_mismatch",
        "value_mismatch",
        "already_current",
        "timeout",
        "cancelled",
        "output_limit",
        "cleanup_failed",
        "internal_error",
    }
)
PROMPTS = {
    "trust": (
        "Run only in your own separate shell, never an agent tool. Accept trust in "
        "this host, binaries, settings, clients, plugins/hooks/MCP and system TLS. "
        "Confirm Doppler analytics are disabled in the existing user config. "
        "Ambient proxy/CA overrides are NOT forwarded. Type ACCEPT-TRUST: "
    ),
    "scope": (
        "Independently verify your OWN Doppler write identity and the runtime "
        "read identity use the SAME workplace and dot-nix/dev_personal. Verify "
        "write, single-key read, audit/history access and bootstrap read scope. "
        "Do not use the SOPS/runtime token here. Type SCOPES-VERIFIED: "
    ),
    "window": (
        "Coordinate EVERY writer of AWS_BEARER_TOKEN_BEDROCK and hold its exclusive "
        "write window through all checks. This is NOT compare-and-swap. If you "
        "cannot exclude concurrent writers, stop. Type EXCLUSIVE-WINDOW: "
    ),
    "lifecycle": (
        "Keep A and B valid; unknown results STOP switching and revocation. "
        "Grok may refresh immediately after publication; save work and arrange "
        "client restart/verification yourself. No result proves client migration. "
        "Record credential IDs and clear the one-time clipboard. Type KEEP-KEYS: "
    ),
    "auth": (
        "Use an existing root-scope login in your private HOME/.doppler, or supply "
        "your OWN existing user token (not a service/bootstrap token). This tool "
        "does not login, refresh or initialize auth. Type LOGIN or TOKEN: "
    ),
    "token": "Existing user-owned Doppler token, hidden (never the SOPS/runtime token): ",
    "workplace": "Expected workplace slug, independently checked in the Doppler console: ",
    "lifetime": (
        "B is the COMPLETE key generated by YOU in IAM console: Amazon Bedrock, "
        "Never expires, no ExpirationDate. Verify boundary/attachments and retain "
        "credential ID, user ARN and creation date. Check the two credential slots; "
        "investigate any unknown credential first. Type NEVER-EXPIRES: "
    ),
    "presence": (
        "Independently check whether the target key is absent or will be "
        "overwritten. Type ABSENT or REPLACE: "
    ),
    "history": (
        "Confirm access to this single key's history and the correct prior A. "
        "For restore, retrieve A yourself in the console and verify it is still "
        "valid in AWS. Never use config-log rollback. Type HISTORY-AVAILABLE: "
    ),
    "label": "Which hidden candidate are you confirming? Type B or A: ",
    "b": "Complete candidate B, hidden: ",
    "a": "Complete prior A from verified single-key history, hidden: ",
    "event": (
        "Exact single-key WRITE EVENT ID for the supplied candidate B (or A when "
        "confirming A), checked in the same workplace/config; NOT a version ID: "
    ),
    "upload": (
        "Approve THIS invocation setting ONLY AWS_BEARER_TOKEN_BEDROCK in "
        "dot-nix/dev_personal, overwriting it if present, within the held window. "
        "There is no automatic retry, rollback or revocation. Type WRITE-ONE-KEY: "
    ),
    "restore": (
        "Approve THIS invocation replacing verified current B with supplied A, "
        "ONLY AWS_BEARER_TOKEN_BEDROCK, within the held window. Other secrets must "
        "remain unchanged. This is not CAS or config rollback. Type RESTORE-ONE-KEY: "
    ),
}


class Stop(Exception):
    def __init__(self, reason: str) -> None:
        self.reason = reason if reason in REASONS else "internal_error"
        super().__init__(self.reason)


def object_value(value: object) -> dict[str, object]:
    if not isinstance(value, dict) or any(not isinstance(k, str) for k in value):
        raise Stop("invalid_response")
    return cast(dict[str, object], value)


def unique_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise Stop("invalid_response")
        result[key] = value
    return result


def invalid_constant(_value: str) -> object:
    raise Stop("invalid_response")


def parse_json(raw: bytes) -> object:
    if len(raw) > MAX_OUTPUT:
        raise Stop("output_limit")
    try:
        return json.loads(
            raw, object_pairs_hook=unique_object, parse_constant=invalid_constant
        )
    except (ValueError, UnicodeError, RecursionError):
        raise Stop("invalid_response") from None


def opaque(value: object, reason: str = "invalid_input") -> bytes:
    if (
        not isinstance(value, str)
        or not 1 <= len(value) <= MAX_SECRET
        or value.startswith(("{", "[", '"'))
    ):
        raise Stop(reason)
    if any(ord(char) < 33 or ord(char) > 126 for char in value):
        raise Stop(reason)
    return value.encode("ascii")


def identifier(value: object, reason: str = "invalid_response") -> str:
    if not isinstance(value, str) or IDENTIFIER.fullmatch(value) is None:
        raise Stop(reason)
    return value


@dataclass(frozen=True)
class Runtime:
    doppler_binary: str

    @classmethod
    def parse(cls, value: object) -> Runtime:
        data = object_value(value)
        if set(data) != {"doppler_binary", "project", "doppler_config", "api_host"}:
            raise Stop("invalid_runtime")
        expected = {"project": PROJECT, "doppler_config": CONFIG, "api_host": API_HOST}
        if any(data[key] != val for key, val in expected.items()):
            raise Stop("invalid_runtime")
        binary = data["doppler_binary"]
        if not isinstance(binary, str) or NIX_BINARY.fullmatch(binary) is None:
            raise Stop("invalid_runtime")
        return cls(binary)


def load_runtime(path: str) -> Runtime:
    try:
        descriptor = os.open(path, os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW)
        with os.fdopen(descriptor, "rb") as stream:
            info = os.fstat(stream.fileno())
            if not stat.S_ISREG(info.st_mode) or info.st_size > MAX_RUNTIME:
                raise Stop("invalid_runtime")
            raw = stream.read(MAX_RUNTIME + 1)
        if len(raw) > MAX_RUNTIME:
            raise Stop("invalid_runtime")
        return Runtime.parse(parse_json(raw))
    except (OSError, ValueError, Stop):
        raise Stop("invalid_runtime") from None


def hidden_input(prompt: str) -> str:
    with warnings.catch_warnings():
        warnings.simplefilter("error", getpass.GetPassWarning)
        try:
            return getpass.getpass(prompt, stream=sys.stderr)
        except (getpass.GetPassWarning, EOFError, OSError):
            raise Stop("input_unavailable") from None


class Questions:
    def __init__(self, prompt: Callable[[str], str]) -> None:
        self.prompt = prompt

    def ask(self, name: str) -> str:
        return self.prompt(f"[{name}] {PROMPTS[name]}")

    def require(self, name: str, answer: str) -> None:
        if self.ask(name) != answer:
            raise Stop("user_declined")


@dataclass(frozen=True)
class CommandResult:
    returncode: int | None = None
    stdout: bytes = field(default=b"", repr=False)
    stderr: bytes = field(default=b"", repr=False)
    started: bool = True
    failure: str | None = None


Runner = Callable[[tuple[str, ...], bytes, Mapping[str, str], float], CommandResult]


@contextmanager
def cancellation(defer: bool) -> Iterator[list[bool]]:
    pending = [False]

    def handle(_signum: int, _frame: object) -> None:
        pending[0] = True
        if not defer:
            raise KeyboardInterrupt

    previous = {
        sig: signal.getsignal(sig)
        for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP)
    }
    try:
        for sig in previous:
            signal.signal(sig, handle)
        yield pending
    finally:
        for sig, handler in previous.items():
            signal.signal(sig, handler)


def signal_group(pid: int, signum: int) -> bool:
    try:
        os.killpg(pid, signum)
        return True
    except ProcessLookupError:
        return True
    except OSError:
        return False


def stop_group(process: subprocess.Popen[bytes]) -> bool:
    terminated = signal_group(process.pid, signal.SIGTERM)
    try:
        process.wait(timeout=CLEANUP_TIMEOUT)
    except subprocess.TimeoutExpired:
        pass
    killed = signal_group(process.pid, signal.SIGKILL)
    try:
        process.wait(timeout=CLEANUP_TIMEOUT)
    except (OSError, subprocess.TimeoutExpired):
        return False
    return terminated and killed


def close_pipe(selector: selectors.BaseSelector, stream: BinaryIO) -> None:
    selector.unregister(stream)
    stream.close()


def transfer(
    selector: selectors.BaseSelector,
    event: selectors.SelectorKey,
    payload: bytes,
    offset: int,
    buffers: dict[str, bytearray],
) -> int:
    stream = cast(BinaryIO, event.fileobj)
    if event.data == "stdin":
        try:
            offset += os.write(event.fd, memoryview(payload)[offset:])
        except BrokenPipeError:
            offset = len(payload)
        if offset == len(payload):
            close_pipe(selector, stream)
        return offset
    chunk = os.read(event.fd, 65536)
    if not chunk:
        close_pipe(selector, stream)
        return offset
    if sum(len(value) for value in buffers.values()) + len(chunk) > MAX_OUTPUT:
        raise Stop("output_limit")
    buffers[event.data].extend(chunk)
    return offset


def poll_pipes(
    selector: selectors.BaseSelector,
    payload: bytes,
    pending: list[bool],
    deadline: float,
) -> dict[str, bytearray]:
    buffers = {"stdout": bytearray(), "stderr": bytearray()}
    offset = 0
    while selector.get_map():
        remaining = deadline - time.monotonic()
        if pending[0]:
            raise Stop("cancelled")
        if remaining <= 0:
            raise Stop("timeout")
        for event, _mask in selector.select(min(remaining, 0.05)):
            offset = transfer(selector, event, payload, offset, buffers)
    return buffers


def register_pipes(
    selector: selectors.BaseSelector, process: subprocess.Popen[bytes]
) -> None:
    streams = {
        "stdin": process.stdin,
        "stdout": process.stdout,
        "stderr": process.stderr,
    }
    for name, stream in streams.items():
        if stream is None:
            raise Stop("internal_error")
        os.set_blocking(stream.fileno(), False)
        selector.register(
            stream,
            selectors.EVENT_WRITE if name == "stdin" else selectors.EVENT_READ,
            name,
        )


def capture(
    process: subprocess.Popen[bytes],
    payload: bytes,
    pending: list[bool],
    timeout: float,
) -> tuple[bytes, bytes]:
    deadline = time.monotonic() + timeout
    with selectors.DefaultSelector() as selector:
        register_pipes(selector, process)
        if not payload:
            close_pipe(selector, cast(BinaryIO, process.stdin))
        buffers = poll_pipes(selector, payload, pending, deadline)
    if pending[0]:
        raise Stop("cancelled")
    try:
        process.wait(timeout=max(0.001, deadline - time.monotonic()))
    except subprocess.TimeoutExpired:
        raise Stop("timeout") from None
    return bytes(buffers["stdout"]), bytes(buffers["stderr"])


def finish_process(process: subprocess.Popen[bytes]) -> bool:
    try:
        return stop_group(process)
    finally:
        for stream in (process.stdin, process.stdout, process.stderr):
            if stream is not None:
                stream.close()


def managed_command(
    argv: tuple[str, ...],
    payload: bytes,
    environment: Mapping[str, str],
    timeout: float,
    pending: list[bool],
) -> CommandResult:
    process: subprocess.Popen[bytes] | None = None
    result = CommandResult(failure="internal_error")
    try:
        process = subprocess.Popen(
            argv,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=dict(environment),
            cwd="/",
            start_new_session=True,
            close_fds=True,
        )
        stdout, stderr = capture(process, payload, pending, timeout)
        result = CommandResult(process.returncode, stdout, stderr)
    except FileNotFoundError:
        result = CommandResult(
            started=process is not None, failure="executable_unavailable"
        )
    except PermissionError:
        result = CommandResult(
            started=process is not None, failure="local_permission_denied"
        )
    except Stop as error:
        result = CommandResult(failure=error.reason)
    except (KeyboardInterrupt, SystemExit):
        result = CommandResult(failure="cancelled")
    except (OSError, ValueError):
        result = CommandResult(started=process is not None, failure="internal_error")
    finally:
        if process is not None and not finish_process(process):
            result = CommandResult(failure="cleanup_failed")
    if pending[0] and result.failure != "cleanup_failed":
        return CommandResult(started=process is not None, failure="cancelled")
    return result


def run_command(
    argv: tuple[str, ...],
    payload: bytes,
    environment: Mapping[str, str],
    timeout: float,
) -> CommandResult:
    if os.name != "posix":
        return CommandResult(started=False, failure="unsupported_platform")
    with cancellation(defer=True) as pending:
        return managed_command(argv, payload, environment, timeout, pending)


def classify(result: CommandResult) -> str:
    if result.failure is not None:
        return result.failure if result.failure in REASONS else "internal_error"
    if len(result.stdout) + len(result.stderr) > MAX_OUTPUT:
        return "output_limit"
    if result.returncode == 0:
        return "ok"
    lowered = result.stderr.lower()
    if b"unable to parse api response" in lowered:
        return "invalid_response"
    hints = (
        b"permission",
        b"forbidden",
        b"unauthorized",
        b"invalid token",
        b"provide a token",
        b"authentication",
    )
    if any(hint in lowered for hint in hints):
        return "permission_or_authentication"
    return "cli_error"


def user_environment(
    environ: Mapping[str, str], questions: Questions
) -> dict[str, str]:
    home = environ.get("HOME", "")
    if not home.startswith("/") or any(ord(char) < 32 for char in home):
        raise Stop("user_config_unavailable")
    directory = Path(home) / ".doppler"
    try:
        directory_info = directory.lstat()
        file_info = (directory / ".doppler.yaml").lstat()
    except OSError:
        raise Stop("user_config_unavailable") from None
    if not stat.S_ISDIR(directory_info.st_mode) or not stat.S_ISREG(file_info.st_mode):
        raise Stop("user_config_permissions")
    if file_info.st_nlink != 1:
        raise Stop("user_config_permissions")
    for info in (directory_info, file_info):
        if info.st_uid != os.getuid() or info.st_mode & 0o077:
            raise Stop("user_config_permissions")
    environment = {"HOME": home, "PATH": "/usr/bin:/bin", "LANG": "C", "NO_COLOR": "1"}
    mode = questions.ask("auth")
    if mode == "TOKEN":
        environment["DOPPLER_TOKEN"] = opaque(questions.ask("token")).decode("ascii")
    elif mode != "LOGIN":
        raise Stop("user_declined")
    return environment


@dataclass(frozen=True)
class Event:
    id: str
    created_at: str
    when: datetime = field(repr=False)


def event_metadata(value: object) -> Event:
    data = object_value(value)
    if data.get("project") != PROJECT or data.get("config") != CONFIG:
        raise Stop("invalid_response")
    event_id = identifier(data.get("id"))
    created = data.get("created_at")
    if not isinstance(created, str) or TIMESTAMP.fullmatch(created) is None:
        raise Stop("invalid_response")
    try:
        when = datetime.fromisoformat(created.replace("Z", "+00:00"))
    except ValueError:
        raise Stop("invalid_response") from None
    return Event(event_id, created, when)


@dataclass(frozen=True, repr=False)
class Change:
    added: str
    removed: str


class Doppler:
    def __init__(
        self,
        runtime: Runtime,
        environment: dict[str, str],
        runner: Runner,
        workplace: str,
        private: tuple[bytes, ...] = (),
    ) -> None:
        self.runtime = runtime
        self.environment = environment
        self.runner = runner
        self.workplace = workplace
        self.private = private
        if "DOPPLER_TOKEN" in environment:
            self.private += (environment["DOPPLER_TOKEN"].encode("ascii"),)
        self.identity: tuple[str, str] | None = None
        self.budget = COMMAND_BUDGET

    def guard_metadata(self, *items: str) -> None:
        if any(
            secret in item.encode("ascii") for secret in self.private for item in items
        ):
            raise Stop("invalid_response")

    def invoke(
        self, command: tuple[str, ...], payload: bytes = b"", scoped: bool = True
    ) -> CommandResult:
        if self.budget <= 0:
            return CommandResult(started=False, failure="timeout")
        argv = (
            self.runtime.doppler_binary,
            "--api-host",
            API_HOST,
            "--no-verify-tls=false",
            "--no-timeout=false",
            "--timeout",
            "10s",
            "--attempts",
            "1",
            "--no-check-version",
            "--enable-dns-resolver=false",
            "--debug=false",
            "--print-config=false",
            "--silent",
            "--scope",
            "/",
            "--config-dir",
            str(Path(self.environment["HOME"]) / ".doppler"),
            "--no-read-env=false"
            if "DOPPLER_TOKEN" in self.environment
            else "--no-read-env",
            *command,
        )
        if scoped:
            argv += ("--project", PROJECT, "--config", CONFIG)
        started = time.monotonic()
        try:
            return self.runner(
                argv, payload, self.environment, min(COMMAND_TIMEOUT, self.budget)
            )
        finally:
            self.budget -= time.monotonic() - started

    def query(self, command: tuple[str, ...], scoped: bool = True) -> object:
        result = self.invoke((*command, "--json"), scoped=scoped)
        category = classify(result)
        if category != "ok":
            raise Stop(category)
        if result.stderr:
            raise Stop("invalid_response")
        return parse_json(result.stdout)

    def check_identity(self) -> None:
        data = object_value(self.query(("me",), scoped=False))
        workplace = object_value(data.get("workplace"))
        if workplace.get("slug") != self.workplace:
            raise Stop("workplace_mismatch")
        actor_type = data.get("type")
        if (
            not isinstance(actor_type, str)
            or not 1 <= len(actor_type) <= 128
            or not actor_type.isprintable()
        ):
            raise Stop("invalid_response")
        identity = (identifier(data.get("slug")), actor_type)
        if self.identity is not None and self.identity != identity:
            raise Stop("identity_changed")
        self.identity = identity

    def current(self) -> bytes | None:
        # CLI 3.76.5 secrets.go:200-243, printer/enclave.go:282-311.
        data = object_value(
            self.query(
                ("secrets", "get", SECRET, "--raw", "--no-exit-on-missing-secret")
            )
        )
        if not data:
            return None
        if set(data) != {SECRET}:
            raise Stop("invalid_response")
        value = object_value(data[SECRET])
        raw = opaque(value.get("raw"), "unreadable_secret")
        computed = opaque(value.get("computed"), "unreadable_secret")
        if raw != computed:
            raise Stop("unreadable_secret")
        return raw

    def recent(self) -> tuple[Event, ...]:
        data = self.query(
            ("configs", "logs", "--page", "1", "--number", str(HISTORY_LIMIT))
        )
        if data is None:
            return ()
        if not isinstance(data, list) or len(data) > HISTORY_LIMIT:
            raise Stop("invalid_response")
        events = tuple(event_metadata(item) for item in data)
        for event in events:
            self.guard_metadata(event.id, event.created_at)
        if len({event.id for event in events}) != len(events):
            raise Stop("invalid_response")
        if any(a.when < b.when for a, b in pairwise(events)):
            raise Stop("invalid_response")
        return events

    def change(self, event: Event) -> Change | None:
        # JSON config logs contain plaintext diff/text; never expose the object.
        self.guard_metadata(event.id, event.created_at)
        data = object_value(self.query(("configs", "logs", "get", event.id)))
        if event_metadata(data) != event:
            raise Stop("concurrent_change")
        diff = data.get("diff")
        if not isinstance(diff, list) or not diff:
            raise Stop("history_unavailable")
        entries = [object_value(item) for item in diff]
        names = [identifier(item.get("name")) for item in entries]
        if len(set(names)) != len(names):
            raise Stop("invalid_response")
        if SECRET not in names:
            return None
        if names != [SECRET]:
            raise Stop("event_not_single_key")
        added, removed = entries[0].get("added"), entries[0].get("removed")
        if not isinstance(added, str) or not isinstance(removed, str):
            raise Stop("history_unavailable")
        return Change(added, removed)

    def stable(self, snapshot: tuple[Event, ...]) -> None:
        if self.recent() != snapshot:
            raise Stop("concurrent_change")
        self.check_identity()


def verify_change(
    change: Change | None, candidate: bytes, previous: bytes | None = None
) -> None:
    if change is None:
        raise Stop("event_not_single_key")
    if change.added.encode("utf-8") != candidate:
        raise Stop("event_value_mismatch")
    if previous is not None and change.removed.encode("utf-8") != previous:
        raise Stop("event_value_mismatch")


def referenced_event(
    doppler: Doppler,
    snapshot: tuple[Event, ...],
    event_id: str,
    candidate: bytes,
    previous: bytes | None = None,
) -> Event:
    index = next((i for i, event in enumerate(snapshot) if event.id == event_id), None)
    if index is None:
        raise Stop("history_unavailable")
    for newer in snapshot[:index]:
        if doppler.change(newer) is not None:
            raise Stop("later_target_edit")
    event = snapshot[index]
    verify_change(doppler.change(event), candidate, previous)
    return event


def new_event(
    doppler: Doppler,
    before: tuple[Event, ...],
    after: tuple[Event, ...],
    candidate: bytes,
    previous: bytes,
) -> Event:
    boundary = len(after)
    if before:
        boundary = next((i for i, event in enumerate(after) if event == before[0]), -1)
    if boundary < 0 or (not before and len(after) == HISTORY_LIMIT):
        raise Stop("history_unavailable")
    changes = [(event, doppler.change(event)) for event in after[:boundary]]
    target_changes = [
        (event, change) for event, change in changes if change is not None
    ]
    if not target_changes:
        raise Stop("history_unavailable")
    if len(target_changes) != 1:
        raise Stop("later_target_edit")
    event, change = target_changes[0]
    verify_change(change, candidate, previous)
    return event


@dataclass(repr=False)
class Inputs:
    a: bytes | None = None
    b: bytes | None = None
    label: str = "B"
    event_id: str | None = None
    presence: str | None = None

    @property
    def candidate(self) -> bytes:
        value = self.b if self.label == "B" else self.a
        if value is None:
            raise Stop("invalid_input")
        return value


@dataclass
class Report:
    action: str = "invalid"
    commit_state: str = "unknown"
    reason: str = "internal_error"
    write_attempted: bool = False
    write_result: str = "not_attempted"
    matches_A: bool | None = None
    matches_B: bool | None = None
    workplace_matches: bool | None = None
    scopes_user_confirmed: bool = False
    exclusive_window_user_confirmed: bool = False
    history_user_confirmed: bool = False
    expected_current_B_verified: bool = False
    event: Event | None = None

    def clear_matches(self) -> None:
        self.matches_A = None
        self.matches_B = None

    def fail(self, reason: str) -> None:
        self.reason = reason if reason in REASONS else "internal_error"
        self.event = None
        if self.commit_state == "confirmed_committed":
            self.commit_state = "unknown"
        if reason == "workplace_mismatch":
            self.workplace_matches = False

    def observe(self, doppler: Doppler, inputs: Inputs) -> bytes | None:
        self.clear_matches()
        current = doppler.current()
        if inputs.a is not None:
            self.matches_A = current == inputs.a
        if inputs.b is not None:
            self.matches_B = current == inputs.b
        return current

    def output(self) -> dict[str, object]:
        return {
            "schema": "bedrock-key-admin/v1",
            "action": self.action,
            "commit_state": self.commit_state,
            "state_scope": "referenced_event"
            if self.action == "confirm"
            else "this_write_attempt",
            "reason": self.reason,
            "project": PROJECT,
            "doppler_config": CONFIG,
            "api_host": API_HOST,
            "secret_name": SECRET,
            "write_attempted": self.write_attempted,
            "write_result": self.write_result,
            "matches_A": self.matches_A,
            "matches_B": self.matches_B,
            "workplace_matches": self.workplace_matches,
            "scopes_user_confirmed": self.scopes_user_confirmed,
            "exclusive_window_user_confirmed": self.exclusive_window_user_confirmed,
            "history_user_confirmed": self.history_user_confirmed,
            "expected_current_B_verified": self.expected_current_B_verified,
            "metadata_verified": self.event is not None,
            "event_id": self.event.id if self.event is not None else None,
            "event_created_at": self.event.created_at
            if self.event is not None
            else None,
            "no_later_target_edit": True if self.event is not None else None,
            "compare_and_swap": False,
            "client_migration_verified": False,
            "may_revoke_keys": False,
            "next_step": "user_verify_clients_keep_keys"
            if self.commit_state == "confirmed_committed"
            else "stop_keep_keys",
        }


def collect_inputs(action: str, questions: Questions, report: Report) -> Inputs:
    values = Inputs()
    if action == "upload":
        questions.require("lifetime", "NEVER-EXPIRES")
        values.presence = questions.ask("presence")
        if values.presence not in ("ABSENT", "REPLACE"):
            raise Stop("user_declined")
        if values.presence == "REPLACE":
            questions.require("history", "HISTORY-AVAILABLE")
            report.history_user_confirmed = True
        values.b = opaque(questions.ask("b"))
    elif action == "restore":
        questions.require("history", "HISTORY-AVAILABLE")
        report.history_user_confirmed = True
        values.label = "A"
        values.a = opaque(questions.ask("a"))
        values.b = opaque(questions.ask("b"))
        if values.a == values.b:
            raise Stop("invalid_input")
    else:
        values.label = questions.ask("label")
        if values.label not in ("A", "B"):
            raise Stop("user_declined")
        candidate = opaque(questions.ask(values.label.lower()))
        if values.label == "A":
            values.a = candidate
        else:
            values.b = candidate
    if action in ("confirm", "restore"):
        values.event_id = identifier(questions.ask("event"), "invalid_input")
    return values


def initial_checks(
    doppler: Doppler, questions: Questions, inputs: Inputs, report: Report
) -> tuple[tuple[Event, ...], bytes | None]:
    doppler.check_identity()
    report.workplace_matches = True
    snapshot = doppler.recent()
    current = report.observe(doppler, inputs)
    if report.action == "upload":
        if (current is None) != (inputs.presence == "ABSENT"):
            raise Stop("presence_mismatch")
        if current == inputs.candidate:
            raise Stop("already_current")
    if report.action == "restore":
        if current != inputs.b:
            raise Stop("value_mismatch")
        referenced_event(
            doppler,
            snapshot,
            cast(str, inputs.event_id),
            cast(bytes, inputs.b),
            inputs.a,
        )
        report.expected_current_B_verified = True
    if report.action != "confirm":
        answer = "WRITE-ONE-KEY" if report.action == "upload" else "RESTORE-ONE-KEY"
        questions.require(report.action, answer)
        if report.observe(doppler, inputs) != current:
            raise Stop("concurrent_change")
        doppler.stable(snapshot)
    return snapshot, current


def perform(
    doppler: Doppler, questions: Questions, inputs: Inputs, report: Report
) -> None:
    before, previous = initial_checks(doppler, questions, inputs, report)
    if report.action == "confirm":
        if previous != inputs.candidate:
            raise Stop("value_mismatch")
        event = referenced_event(
            doppler, before, cast(str, inputs.event_id), inputs.candidate
        )
        doppler.stable(before)
    else:
        report.write_attempted = True
        report.commit_state = "unknown"
        report.write_result = "internal_error"
        report.clear_matches()
        # CLI 3.76.5 api.go:331-339 can fail AFTER the POST committed.
        result = doppler.invoke(
            ("secrets", "set", SECRET, "--no-interactive"), inputs.candidate
        )
        category = classify(result)
        report.write_result = category
        if category == "ok" and (result.stdout or result.stderr):
            report.write_result = "invalid_response"
        if not result.started:
            report.commit_state = "confirmed_not_submitted"
            raise Stop(category if category != "ok" else "internal_error")
        if category in {
            "timeout",
            "cancelled",
            "output_limit",
            "cleanup_failed",
            "internal_error",
        }:
            raise Stop(category)
        if report.observe(doppler, inputs) != inputs.candidate:
            raise Stop("value_mismatch")
        after = doppler.recent()
        event = new_event(doppler, before, after, inputs.candidate, previous or b"")
        doppler.stable(after)
    doppler.guard_metadata(event.id, event.created_at)
    report.event = event
    report.commit_state = "confirmed_committed"
    report.reason = "verified_event_and_value"


def administer(
    runtime: Runtime,
    action: str,
    *,
    runner: Runner = run_command,
    prompt: Callable[[str], str] = hidden_input,
    environ: Mapping[str, str] | None = None,
) -> Report:
    report = Report(action=action if action in ACTIONS else "invalid")
    if action in ("upload", "restore"):
        report.commit_state = "confirmed_not_submitted"
    try:
        if action not in ACTIONS:
            raise Stop("invalid_arguments")
        if os.name != "posix":
            raise Stop("unsupported_platform")
        with cancellation(defer=False):
            questions = Questions(prompt)
            questions.require("trust", "ACCEPT-TRUST")
            questions.require("scope", "SCOPES-VERIFIED")
            report.scopes_user_confirmed = True
            questions.require("window", "EXCLUSIVE-WINDOW")
            report.exclusive_window_user_confirmed = True
            questions.require("lifecycle", "KEEP-KEYS")
            environment = user_environment(
                os.environ if environ is None else environ, questions
            )
            workplace = identifier(questions.ask("workplace"), "invalid_input")
            inputs = collect_inputs(action, questions, report)
            private = tuple(
                value for value in (inputs.a, inputs.b) if value is not None
            )
            doppler = Doppler(runtime, environment, runner, workplace, private)
            if inputs.event_id is not None:
                doppler.guard_metadata(inputs.event_id)
            perform(doppler, questions, inputs, report)
    except Stop as error:
        report.fail(error.reason)
    except (KeyboardInterrupt, SystemExit, EOFError):
        report.fail("cancelled")
    except Exception:  # noqa: BLE001 - Unexpected exceptions may contain secret values.
        report.fail("internal_error")
    return report


def main(argv: Sequence[str] | None = None) -> int:
    arguments = list(sys.argv[1:] if argv is None else argv)
    report = Report(reason="invalid_arguments")
    try:
        if len(arguments) not in (1, 2):
            raise Stop("invalid_arguments")
        action = arguments[1] if len(arguments) == 2 else "upload"
        if action not in ACTIONS:
            raise Stop("invalid_arguments")
        runtime = load_runtime(arguments[0])
        report = administer(runtime, action)
    except Stop as error:
        report.fail(error.reason)
    except (KeyboardInterrupt, SystemExit):
        report.fail("cancelled")
    except Exception:  # noqa: BLE001 - Unexpected exceptions may contain secret values.
        report.fail("internal_error")
    print(json.dumps(report.output(), sort_keys=True, separators=(",", ":")))
    return 0 if report.commit_state == "confirmed_committed" else 2


if __name__ == "__main__":
    sys.exit(main())
