#!/usr/bin/env bash
#MISE description="Use native command to do nix gc"
#MISE raw=true

home-manager expire-generations '0s'
nix profile wipe-history --older-than '4d'
nix store gc
sudo nix store gc
nix-store --optimise
sudo nix-store --optimise

# vim: ft=sh
